services:
  - type: web
    name: avail-railway-platform
    env: python
    buildCommand: "pip install -r requirements.txt && cd frontend && npm install && npm run build"
    startCommand: "python run_avail.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: NODE_VERSION
        value: 20.0.0